# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: location.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0elocation.proto\"`\n\x0fLocationMessage\x12\x11\n\tperson_id\x18\x01 \x01(\x05\x12\x10\n\x08latitude\x18\x02 \x01(\t\x12\x11\n\tlongitude\x18\x03 \x01(\t\x12\x15\n\rcreation_time\x18\x04 \x01(\t\":\n\x13LocationMessageList\x12#\n\tlocations\x18\x01 \x03(\x0b\x32\x10.LocationMessage\"\x07\n\x05\x45mpty\"A\n\x07Request\x12\x11\n\tperson_id\x18\x01 \x01(\x05\x12\x10\n\x08latitude\x18\x02 \x01(\t\x12\x11\n\tlongitude\x18\x03 \x01(\t2\\\n\x0fLocationService\x12$\n\x06\x43reate\x12\x08.Request\x1a\x10.LocationMessage\x12#\n\x03Get\x12\x06.Empty\x1a\x14.LocationMessageListb\x06proto3')



_LOCATIONMESSAGE = DESCRIPTOR.message_types_by_name['LocationMessage']
_LOCATIONMESSAGELIST = DESCRIPTOR.message_types_by_name['LocationMessageList']
_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_REQUEST = DESCRIPTOR.message_types_by_name['Request']
LocationMessage = _reflection.GeneratedProtocolMessageType('LocationMessage', (_message.Message,), {
  'DESCRIPTOR' : _LOCATIONMESSAGE,
  '__module__' : 'location_pb2'
  # @@protoc_insertion_point(class_scope:LocationMessage)
  })
_sym_db.RegisterMessage(LocationMessage)

LocationMessageList = _reflection.GeneratedProtocolMessageType('LocationMessageList', (_message.Message,), {
  'DESCRIPTOR' : _LOCATIONMESSAGELIST,
  '__module__' : 'location_pb2'
  # @@protoc_insertion_point(class_scope:LocationMessageList)
  })
_sym_db.RegisterMessage(LocationMessageList)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'location_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'location_pb2'
  # @@protoc_insertion_point(class_scope:Request)
  })
_sym_db.RegisterMessage(Request)

_LOCATIONSERVICE = DESCRIPTOR.services_by_name['LocationService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOCATIONMESSAGE._serialized_start=18
  _LOCATIONMESSAGE._serialized_end=114
  _LOCATIONMESSAGELIST._serialized_start=116
  _LOCATIONMESSAGELIST._serialized_end=174
  _EMPTY._serialized_start=176
  _EMPTY._serialized_end=183
  _REQUEST._serialized_start=185
  _REQUEST._serialized_end=250
  _LOCATIONSERVICE._serialized_start=252
  _LOCATIONSERVICE._serialized_end=344
# @@protoc_insertion_point(module_scope)
