apiVersion: v1
kind: Service
metadata:
  labels:
    service: kafka-api
  name: kafka-api
spec:
  ports:
  - name: "5010"
    port: 5010
    targetPort: 5010
    nodePort: 30010
  selector:
    service: kafka-api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: kafka-api
  name: kafka-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: kafka-api
  template:
    metadata:
      labels:
        service: kafka-api
    spec:
      containers:
      - image: jagadeesh8877/kafka-api:latest
        name: kafka-api
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
        - name: GRPC_PORT
          valueFrom:
            configMapKeyRef:
              name: grpc-port
              key: GRPC_PORT
        - name: KAFKA_URI
          valueFrom:
            configMapKeyRef:
              name: kafka-uri
              key: KAFKA_URI
      restartPolicy: Always
